Adding regression make command

diff --git a/bp_be/syn/Makefile b/bp_be/syn/Makefile
--- a/bp_be/syn/Makefile
+++ b/bp_be/syn/Makefile
@@ -1,4 +1,4 @@
-## Set common environment variables
+# Set common environment variables
 TOP ?= $(shell git rev-parse --show-toplevel)
 
 include $(TOP)/Makefile.common
@@ -10,13 +10,31 @@ REPORT_PATH := $(BP_BE_DIR)/syn/reports
 
 # Default ROM to example
 DESIGN_NAME ?= bp_be_top
-ROM_NAME    ?= bp_example_rom
 TB          ?= bp_be_trace_demo
 
 .EXPORT_ALL_VARIABLES:
 
 include $(BP_COMMON_DIR)/syn/Makefile.common
 include $(BP_COMMON_DIR)/syn/Makefile.dc
+include $(BP_COMMON_DIR)/syn/Makefile.regress
 include $(BP_COMMON_DIR)/syn/Makefile.verilator
 include $(BP_COMMON_DIR)/syn/Makefile.vcs
+
+DCACHE_AXE_TEST_DIR = $(BP_BE_DIR)/test/tb/bp_be_dcache/dcache_axe_test
+
+regress: regress.be
+regress.be: regress.v check_design.syn
+	$(MAKE) lint.v || true
+	$(MAKE) lint.sc || true
+	for lce in 2 4 8 16; do \
+		echo "Running $$lce LCE AXE TEST"; \
+		$(MAKE) -C $(DCACHE_AXE_TEST_DIR) NUM_LCE_P=$$lce NUM_INSTR_P=2500 \
+		| tee $(LOG_PATH)/vcs/dcache_axe_test_$$lce.sim.log; \
+		$(MAKE) -C $(DCACHE_AXE_TEST_DIR) axe \
+		| tee $(LOG_PATH)/vcs/dcache_axe_test_$$lce.axe.log; \
+		grep "OK" $(LOG_PATH)/vcs/dcache_axe_test_$$lce.axe.log \
+		&& echo "$$lce test: OK" >> $(REPORT_PATH)/vcs/dcache_axe_test.rpt \
+		|| echo "$$lce test: FAIL" >> $(REPORT_PATH)/vcs/dcache_axe_test.rpt; \
+		grep "FAIL" $(REPORT_PATH)/vcs/dcache_axe_test.rpt | tee -a $(REPORT_PATH)/vcs/dcache_axe_test.err; \
+	done
 
diff --git a/bp_common/syn/Makefile.dc b/bp_common/syn/Makefile.dc
--- a/bp_common/syn/Makefile.dc
+++ b/bp_common/syn/Makefile.dc
@@ -6,16 +6,14 @@ DC_RUN_DIR := $(SYN_PATH)/run_dc
 
 .PHONY: deps.syn check_design.syn lookup.syn clean.syn
 
-LOG_DIR   = $(LOG_PATH)/dc
-LOG_FILE ?= $(LOG_DIR)/$(TB)_check_design.log  
-ERR_FILE ?= $(LOG_DIR)/$(TB)_check_design.err
-
 deps.syn:
 	$(eval include $(TB_PATH)/$(TB)/Makefile.frag)
 	$(eval LOG_DIR  := $(LOG_PATH)/dc)
+	$(eval REPORT_DIR := $(REPORT_PATH)/dc)
 	$(eval LOG_FILE := $(LOG_DIR)/$(TB)_check_design.log)
 	$(eval ERR_FILE := $(LOG_DIR)/$(TB)_check_design.err)
 	$(shell mkdir -p $(LOG_DIR))
+	$(shell mkdir -p $(REPORT_DIR))
 	$(shell mkdir -p $(DC_RUN_DIR))
 	@grep -v -e "^\#" $(SYN_PATH)/flist.vcs > $(DC_RUN_DIR)/flist.vcs
 
@@ -29,12 +27,18 @@ deps.syn:
 check_design.syn: deps.syn
 	cd $(DC_RUN_DIR); \
 	$(DC_SHELL) -64bit -f $(BP_COMMON_DIR)/syn/tcl/dc_elab.tcl | tee -i $(LOG_FILE)
-	@grep --color      "^Error"                               $(LOG_FILE) | tee -a $(ERR_FILE) || true \
-	@grep --color      "Complex logic will not be considered" $(LOG_FILE) | tee -a $(ERR_FILE) || true \
-	@grep --color -B 3 "*** Presto compilation terminated"    $(LOG_FILE) | tee -a $(ERR_FILE) || true \
-	@grep --color      "unresolved references."               $(LOG_FILE) | tee -a $(ERR_FILE) || true \
-	@grep --color      "Cannot find the design"               $(LOG_FILE) | tee -a $(ERR_FILE) || true \
+	@grep --color      "^Error"                               $(LOG_FILE) | tee -a $(ERR_FILE) || true
+	@grep --color      "Complex logic will not be considered" $(LOG_FILE) | tee -a $(ERR_FILE) || true
+	@grep --color -B 3 "*** Presto compilation terminated"    $(LOG_FILE) | tee -a $(ERR_FILE) || true
+	@grep --color      "unresolved references."               $(LOG_FILE) | tee -a $(ERR_FILE) || true
+	@grep --color      "Cannot find the design"               $(LOG_FILE) | tee -a $(ERR_FILE) || true
 	@grep --color      "undeclared symbol"                    $(LOG_FILE) | tee -a $(ERR_FILE) || true
+	if [[ -s $(ERR_FILE) ]]; then \
+		echo "Design Compiler check_synth: FAILED" | tee $(REPORT_DIR)/$(TB)_check_synth.rpt; \
+		cp $(ERR_FILE) $(REPORT_DIR)/$(TB)_check_synth_err.rpt; \
+	else \
+		echo "Design Compiler check_synth: PASSED" | tee $(REPORT_DIR)/$(TB)_check_synth.rpt; \
+	fi;
 
 # This target allows users to look up commands and message codes for
 # DesignCompiler. If there is a message with a code (e.g. LINT-1) then you can
